apiVersion: v1
kind: Service
metadata:
  name: {{ template "urly.mysql" . }}-service
  labels:
    {{- include "urly.mysql.labels" . | nindent 4 }}
spec:
  ports:
    - port: 3306
  selector:
    {{- include "urly.mysql.labels" . | nindent 4 }} 
