apiVersion: v1
kind: Secret
metadata:
  name: {{ template "urly.mysql" . }}-secret
  labels: 
    {{- include "urly.mysql.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_PASSWORD: {{ template "urly.mysql.encryptedPassword" . }}
  MYSQL_ROOT_PASSWORD: {{ template "urly.mysql.encryptedRootPassword" . }}
