apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "urly.redis" . }}-statefulset
  labels:
    {{- include "urly.redis.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: {{ template "urly.redis" . }}
  selector:
    matchLabels:
      {{- include "urly.redis.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "urly.redis.labels" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          {{- include "urly.redis.image" . | nindent 10 }}
          ports:
            - name: redis
              containerPort: 6379
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 300
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 1
            periodSeconds: 10
          envFrom:
            - secretRef:
                name: "{{ template "urly.redis" . }}"
          volumeMounts:
            - name: redis-data
              mountPath: /var/lib/redis
          args: ["--requirepass", "$(REDIS_PASSWORD)"]
  volumeClaimTemplates:
    - metadata:
        labels:
          {{- include "urly.redis.labels" . | nindent 10 }}
        name: redis-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
