apiVersion: v1
kind: Secret
metadata:
  name: {{ template "urly.redis" . }}-secret
  labels:
    {{- include "urly.redis.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_PASSWORD: {{ template "urly.redis.encryptedPassword" . }}