apiVersion: v1
kind: Service
metadata:
  name: {{ template "urly.redis" . }}-service
  labels:
    {{- include "urly.redis.labels" . | nindent 4 }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    {{- include "urly.redis.labels" . | nindent 4 }}
