# Default values for urly.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global settings
# -- Override the name of the chart
nameOverride: ""  
# -- Override the full name of the chart
fullnameOverride: ""  


imagePullSecrets:
# -- List of secret names to use for pulling images
  - name: "ghcr"  


# MySQL configuration
mysql:
  annotations: {}
  # -- Image pull policy for MySQL
  pullPolicy: "IfNotPresent"  
  # -- Username for MySQL
  username: ""  
  # -- Root password for MySQL
  rootPassword: ""
  # -- Password for the MySQL user
  password: ""

# Redis configuration
redis:
  # -- Image pull policy for Redis
  pullPolicy: "IfNotPresent"
  # -- Password for Redis 
  password: ""  

# Urly web server configuration
urlyWebServer:
  image:
    # -- web server repo
    repository: "ghcr.io/gr2u/url-cut-web-server"
    # -- web server  image tag
    tag: ""
    # -- Image pull policy for the web server
    pullPolicy: "IfNotPresent"  

# Urly API server configuration
urlyApiServer:
  # -- ingress host name and app_host for short url prefix hostname
  appHost: "gr2u.xyz"
  # -- Number of replicas for the API server
  replicas: 3  
  image:
    # -- API server image repository
    repository: "ghcr.io/gr2u/url-cut-api-server" 
    # -- API server image tag
    tag: "0.0.25-dev" 
    # -- Image pull policy for the API server
    pullPolicy: "IfNotPresent"  

# Select cloud provider 
# -- Cloud provider type (e.g., gcp, aws, azure), it's for different settings for ingress controller and annotations at cloud providers.
cloudProvider: "gcp"  

# Cloud provider configuration
gcp: # GCP
  annotations:
    # -- Using google ingress controller 
    kubernetes.io/ingress.class: gce 
    kubernetes.io/ingress.allow-http: "true"
    # -- Static IP name to use with ingress 
    kubernetes.io/ingress.global-static-ip-name: ingress-ip 
    # -- Cert issuer
    cert-manager.io/issuer: letsencrypt-production  



