apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes auto;
    error_log /var/log/nginx/error.log notice;
    pid /run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

        map $http_user_agent $loggable {
            ~*GoogleHC/1\.0  0;
            default           1;
        }

        access_log /var/log/nginx/access.log combined if=$loggable;
        root /usr/share/nginx/html;
        index index.html;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 120;
        types_hash_max_size 2048;

        server {
            listen 80;

            location = / {
                try_files /index.html =404;
            }
            location /static/ {
                alias /usr/share/nginx/html/static/; # Замените на фактический путь к папке статик
            }
            location = /favicon.ico {
                try_files /favicon.ico =404;
            }
            

            
            location / {
            
                proxy_pass http://{{ template "urly.api-server" . }}-service:5000/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /shorten {
                proxy_pass http://{{ template "urly.api-server" . }}-service:5000/shorten;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            location /register {
                proxy_pass http://{{ template "urly.api-server" . }}-service:5000/register;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /login {
                proxy_pass http://{{ template "urly.api-server" . }}-service:5000/login;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            location /health {
                access_log off;
                return 200 "healthy\n";
            }
        }
    }
