apiVersion: v1
kind: Service
metadata:
  name: {{ template "urly.web-server" . }}
  labels:
    {{- include "urly.web-server.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
  selector:
    {{- include "urly.web-server.labels" . | nindent 4 }}

