name: Release
on:
  push:
    branches:
      - 'main'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      security-events: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
      
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.1'
          
      - name: install helm-docs
        run: |
          cd /tmp
          wget https://github.com/norwoodj/helm-docs/releases/download/v${{env.HELM_DOCS_VERSION}}/helm-docs_${{env.HELM_DOCS_VERSION}}_Linux_x86_64.tar.gz
          tar -xvf helm-docs_${{env.HELM_DOCS_VERSION}}_Linux_x86_64.tar.gz
          sudo mv helm-docs /usr/local/sbin
        env:
          HELM_DOCS_VERSION: '1.7.0'
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          framework: helm
          directory: helm/
          output_format: sarif
          output_file_path: ./results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif

      - name: Install dependencies
        run: npm install
      
      - name: Generate release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.PRIVATE_ACCESS_TOKEN }}   
